# Generated by Django 4.2.4 on 2023-09-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_place1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place1',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='place1',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='place1',
            old_name='name',
            new_name='name1',
        ),
    ]
