# Generated by Django 4.2.4 on 2023-09-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_rename_desc_place1_desc1_rename_img_place1_img1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place1',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='place1',
            old_name='img1',
            new_name='img',
        ),
    ]
