# Generated by Django 4.2.4 on 2023-09-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_rename_desc1_place1_desc_rename_img1_place1_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place1',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='place1',
            old_name='img',
            new_name='img1',
        ),
    ]
